testapp/config/routes.rb
Rails.application.routes.draw do
  resources :achievements, only: %i[create new]

  root to: 'welcome#index'
end

testapp/app/models/achievement.rb
# Achievement model class inheriting form application record
class Achievement < ApplicationRecord
  validates :title, presence: true

  enum privacy: %i[public_access private_access friends_access]
end

testapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

testapp/app/controllers/achievements_controller.rb
# Achievements controller
class AchievementsController < ApplicationController
  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      redirect_to root_path, notice: 'Achievement has been created'
    else
      render :new
    end
  end

  private

  def achievement_params
    params.require(:achievement)
          .permit(:title, :description, :privacy, :cover_image, :featured)
  end
end

testapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

testapp/app/controllers/welcome_controller.rb
# welcome controller
class WelcomeController < ApplicationController
  def index; end
end

testapp/app/helpers/application_helper.rb
module ApplicationHelper
end

testapp/app/views/achievements/index.html.erb
<h3>Hello</h3>

testapp/app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies].map { |k, v| [k.split('_').first.capitalize, k] } %>
  <%= f.input :featured, label: 'Featured achievement' %>
  <%= f.input :cover_image, as: :file %>
  <%= f.submit 'Create Achievement', class: 'btn btn-primary' %>
<% end %>

testapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Achievement App', root_path, :class => 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to 'New Achievement', new_achievement_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

testapp/app/views/welcome/index.html.erb
<h1>Welcome</h1>